### ISSUE TITLE
2D Image Plot Coordinate Units Disagree with Axis Labels

### ISSUE THREAD

**Issue by DanRyanIrish** [sunpy/ndcube#183]
### Description

When ```NDCube.plot()``` produces a 2D image plot using the WCS to calculate the axes coordinates, the units in of the axis values do not necessarily correspond those in the axis label which are derived from the ```wcs.wcs.cunit``` attribute.

Where can the units actually used in the transformation be found?

### Steps to Reproduce

1. Extract sample data from sunpy Map and put into an NDCube
```python
>>> import sunpy.map
>>> import sunpy.data.sample
>>> from ndcube import NDCube
>>> aia_map = sunpy.map.Map(sunpy.data.sample.AIA_171_IMAGE)
>>> aia_cube = NDCube(aia_map.data, aia_map.wcs)
```
2. Plot image
```python
>>> aia_cube.plot(vmax=3000)
```
3. Notice that the axis labels give units of ```[deg]```, derived from ```aia_cube.wcs.wcs.cunit```.  But the axis tick values are clearly in arcsec.  Is there somewhere where the units actually used are stored?

### System Details

  - ndcube Version: master
  - SunPy  Version: 1.0.0
  - Python Version: 3.7.3
  - OS information: Mac OS X

**Comment by Cadair** [comment]
So this bug is because we are asking the wrong thing for the units of the plot. We are inspecting the units of the `wcs.wcs` object:

https://github.com/sunpy/ndcube/blob/master/ndcube/mixins/plotting.py#L228

When what we should be doing is asking WCSAxes what units we are in (they very much do not have to be the same, and in fact WCSAxes defaults HPLN / HPLT to arcseconds explicitly in the [astropy source](https://github.com/astropy/astropy/blob/7ebe954bd6eeac32474339cb560019a1e9a45ede/astropy/visualization/wcsaxes/utils.py#L130).

What we need to do is:
```python
ax.coords[0].fomat_unit
```
which give you an astropy Unit object with the unit WCSAxes is using to display that axis.

**Comment by Cadair** [comment]
So this bug is because we are asking the wrong thing for the units of the plot. We are inspecting the units of the `wcs.wcs` object:

https://github.com/sunpy/ndcube/blob/master/ndcube/mixins/plotting.py#L228

When what we should be doing is asking WCSAxes what units we are in (they very much do not have to be the same, and in fact WCSAxes defaults HPLN / HPLT to arcseconds explicitly in the [astropy source](https://github.com/astropy/astropy/blob/7ebe954bd6eeac32474339cb560019a1e9a45ede/astropy/visualization/wcsaxes/utils.py#L130).

What we need to do is:
```python
ax.coords[0].fomat_unit
```
which give you an astropy Unit object with the unit WCSAxes is using to display that axis.
