### ISSUE TITLE
Slicing with Ellipsis gives wrong axis types

### ISSUE THREAD

**Issue by tiagopereira** [sunpy/ndcube#216]
### Description

Slicing an `NDCube` object with an Ellipsis leads to incorrect slicing of the `world_axis_physical_types`. For example, from the documentation:

```python
import numpy as np
import astropy.wcs
from ndcube import NDCube

data = np.ones((3, 4, 5))
wcs_input_dict = {
'CTYPE1': 'WAVE    ', 'CUNIT1': 'Angstrom', 'CDELT1': 0.2, 'CRPIX1': 0, 'CRVAL1': 10, 'NAXIS1': 5,
'CTYPE2': 'HPLT-TAN', 'CUNIT2': 'deg', 'CDELT2': 0.5, 'CRPIX2': 2, 'CRVAL2': 0.5, 'NAXIS2': 4,
'CTYPE3': 'HPLN-TAN', 'CUNIT3': 'deg', 'CDELT3': 0.4, 'CRPIX3': 2, 'CRVAL3': 1, 'NAXIS3': 3}
input_wcs = astropy.wcs.WCS(wcs_input_dict)

my_cube = NDCube(data, input_wcs)
```

Doing `my_cube[:, :, 0]` will give the axis types `('custom:pos.helioprojective.lon', 'custom:pos.helioprojective.lat')`, as expected:

```
In [4]: my_cube[:, :, 0]
Out[4]:
NDCube
---------------------
WCS Keywords

Number of WCS axes: 3
CTYPE : 'WAVE'  'HPLT-TAN'  'HPLN-TAN'
CRVAL : 1e-09  0.5  1.0
CRPIX : 0.0  2.0  2.0
PC1_1 PC1_2 PC1_3  : 1.0  0.0  0.0
PC2_1 PC2_2 PC2_3  : 0.0  1.0  0.0
PC3_1 PC3_2 PC3_3  : 0.0  0.0  1.0
CDELT : 2.0000000000000002e-11  0.5  0.4
NAXIS : 1  4  3
---------------------
Length of NDCube: [3. 4.] pix
Axis Types of NDCube: ('custom:pos.helioprojective.lon', 'custom:pos.helioprojective.lat')
```

Slicing as  `my_cube[..., 0]` should give the same result. The data seem correctly sliced, but it will keep the second axis type as wavelength, which is incorrect:

```
In [5]: my_cube[..., 0]
Out[5]:
NDCube
---------------------
WCS Keywords

Number of WCS axes: 3
CTYPE : 'WAVE'  'HPLT-TAN'  'HPLN-TAN'
CRVAL : 1e-09  0.5  1.0
CRPIX : 0.0  2.0  2.0
PC1_1 PC1_2 PC1_3  : 1.0  0.0  0.0
PC2_1 PC2_2 PC2_3  : 0.0  1.0  0.0
PC3_1 PC3_2 PC3_3  : 0.0  0.0  1.0
CDELT : 2.0000000000000002e-11  0.5  0.4
NAXIS : 5  4  1
---------------------
Length of NDCube: [3. 4.] pix
Axis Types of NDCube: ('custom:pos.helioprojective.lon', 'em.wl')
```

### System Details

  - ndcube Version: 1.2.1
  - SunPy  Version: 0.9.8
  - Python Version: 3.7.3
  - OS information: macOS 10.14.6, python from conda

**Comment by DanRyanIrish** [comment]
Hi @tiagopereira.  Thanks for raising this issue.  Slicing with ellipses is currently not supported by ```NDCube```.  Although it does not crash and slices the data correctly, it does not slice the WCS correctly.  It isn't just a matter of the ```world_axis_physical_types```.  There are plans for ndcube 2.0 that will completely change the underlying WCS infrastructure.  As part of this slicing with ellipses should be supported.  Because of this, my initial feeling is it would be not worth the effort to support ellipsis slicing for ndcube 1.x.  However, if you have an urgent use case that would be interesting to hear.

Either way, in the meantime ```NDCube``` should raise a useful error when users try to slice with ellipses.  I can add that and open a PR.

**Comment by tiagopereira** [comment]
I see. Probably makes sense to wait for ndcube 2.0.
