### ISSUE TITLE
Support more ctypes?

### ISSUE THREAD

**Issue by PyDL** [sunpy/ndcube#226]
Hi,

Thank you for providing this fantastic package. Do you have any plan to add support of more ctypes? Currently, I have found this package does not support the following ctypes: "CRLT-CEA", "CRLN-CEA" and "HGLT-CEA"/"HGLN-CEA", as well as "HPRZ".

The "CEA" ctypes are quite useful, as they are widely used in e.g., the HMI vector magnetic field data, which are usually used to perform non-linear force free field extrapolations and forced field extrapolations.

Thank you.

**Comment by Cadair** [comment]
hey @PyDL 

Am I right in thinking that we currently just raise a warning if we don't understand the CTYPE?

**Comment by PyDL** [comment]
> hey @PyDL
> 
> Am I right in thinking that we currently just raise a warning if we don't understand the CTYPE?

hey @Cadair yes, currently the warnings look like 

_UserWarning: CTYPE not recognized by ndcube. Please raise an issue at https://github.com/sunpy/ndcube/issues citing the unsupported CTYPE as we'll include it: CTYPE = CRLN-CEA
  "CTYPE = {}".format(ctype[i])_

**Comment by DanRyanIrish** [comment]
Hi @PyDL.  Thanks for getting in contact with us and apologies for the delayed response due to the holidays.  We are very happy to support more ctypes and felt that best way to decide which ones was to let users tell us through issues like this one.  So thanks for raising!

ndcube "supports" ctypes via a dictionary that maps each ctype to a IVOA UCD1 controlled vocabulary phrase.  This vocabulary defines a standard for coordinates and properties across astronomy which is more generic and more easily machine- and human-readable. An explanation of IVOA UCD1 controlled vocabulary can be found [here](http://www.ivoa.net/documents/REC/UCD/UCDlist-20070402.html) while the dictionary is defined in the ndcube code [here](https://github.com/sunpy/ndcube/blob/master/ndcube/utils/wcs.py#L35).  All that is required from a coding point of view is to add entries to this dictionary for the ctypes you like and open a PR.

In doing so however, we must decide what IVOA UCD1 phrases should be used for these ctypes.  If one doesn't already exist (which is most likely) we can create own own with the ```custom:``` prefix, for example as we have done with ```HPLN-TAN```.  I am not very familiar with the ctypes you mention but if you take a look at the IVOA UCD1 standard, I'll try to understand what these ctypes are.  We can then agree what phrases should be and add them to the dictionary.

**Comment by DanRyanIrish** [comment]
Hi @PyDL.  I've come up with some suggestions for the CEA ctypes you mentioned.
```
CRLT: custom:pos.heliographic.carrington.lat
CRLN: custom:pos.heliographic.carrington.lon
HGLT: custom:pos.heliographic.stonyhurst.lon
HGLN: custom:posheliographic.stonyhurst.lat
```
I'll explain why I chose each component of each term.  I used ```custom:``` as there isn't currently an IVOA UCD1 word that described these ctypes as far as I know.  ```custom:``` highlights this to the user and the community to help new standards be agreed.  This is something we have already impemented for ```HPLN```/```HPLT```.

Second, ```pos``` is the primary category of these properties, i.e. positional coordinates.  This is an approved primary category of the IVOA UCD1 scheme.

Third, ```heliographic``` as this is the the next broadest class of coordinate system we are using.  An alternative would be ```heliocentric.heliographic``` as ```pos.heliocentric``` is an approved IVOA UCD1 word and if I understand correctly, both CRLN/CRLT and HGLN/HGLT have their origins at the center of the Sun.  Therefore it could be argues that heliographic coordinate systems are types of heliocentric ones?  However, in solar at least, heliocentric and heliographic are used distinctly where heliocentric requires information of the observer position while heliographic requires information on the time of observation.  Also, ```pos.heliocentric.heliographic``` starts getting a bit long-winded.  But perhaps this is a decision open to debate.

Fourth, ```carrington``` and ```stonyhurst``` define the type of heliographic coordinate system being used.  This discards the information as to whether we are using the Carrington Time or Carrington Rate based systems.  It also discards that the cylindrical equivalent area is being used.  However, this may be sufficient for our purposes as the label we are defining is aiming to describe the physical property, not necessarily the projection used to obtain it.  The full ctype is still stored in the WCS information and so can still be utilized in the coordinate transformation infrastructure.  As an example, we currently do support ```HPLN-TAN``` as a ctype but its IVOA UCD1 word is ```custom:pos.helioprojective.lon```.  The ```TAN``` is not represented because the physical property is helioprojective longitude, while the ```TAN``` simply describes the projection used to obtain it.  The ```TAN``` is still known by the WCS and so the correct transformations are still implemented.  Do you agree with this or would you say that the projection used leads to a fundamentally different types of latitude and longitude?

Finally, ```lat```/```lon```, defined whether the property is latitude or longitude.

Let me know your thoughts and whether you have any suggestions or questions.

**Comment by DanRyanIrish** [comment]
@PyDL, could you also tell me what ```HPRZ``` stands for?

**Comment by PyDL** [comment]
> Hi @PyDL. I've come up with some suggestions for the CEA ctypes you mentioned.
> 
> ```
> CRLT: custom:pos.heliographic.carrington.lat
> CRLN: custom:pos.heliographic.carrington.lon
> HGLT: custom:pos.heliographic.stonyhurst.lon
> HGLN: custom:posheliographic.stonyhurst.lat
> ```
> 
> I'll explain why I chose each component of each term. I used `custom:` as there isn't currently an IVOA UCD1 word that described these ctypes as far as I know. `custom:` highlights this to the user and the community to help new standards be agreed. This is something we have already impemented for `HPLN`/`HPLT`.
> 
> Second, `pos` is the primary category of these properties, i.e. positional coordinates. This is an approved primary category of the IVOA UCD1 scheme.
> 
> Third, `heliographic` as this is the the next broadest class of coordinate system we are using. An alternative would be `heliocentric.heliographic` as `pos.heliocentric` is an approved IVOA UCD1 word and if I understand correctly, both CRLN/CRLT and HGLN/HGLT have their origins at the center of the Sun. Therefore it could be argues that heliographic coordinate systems are types of heliocentric ones? However, in solar at least, heliocentric and heliographic are used distinctly where heliocentric requires information of the observer position while heliographic requires information on the time of observation. Also, `pos.heliocentric.heliographic` starts getting a bit long-winded. But perhaps this is a decision open to debate.
> 
> Fourth, `carrington` and `stonyhurst` define the type of heliographic coordinate system being used. This discards the information as to whether we are using the Carrington Time or Carrington Rate based systems. It also discards that the cylindrical equivalent area is being used. However, this may be sufficient for our purposes as the label we are defining is aiming to describe the physical property, not necessarily the projection used to obtain it. The full ctype is still stored in the WCS information and so can still be utilized in the coordinate transformation infrastructure. As an example, we currently do support `HPLN-TAN` as a ctype but its IVOA UCD1 word is `custom:pos.helioprojective.lon`. The `TAN` is not represented because the physical property is helioprojective longitude, while the `TAN` simply describes the projection used to obtain it. The `TAN` is still known by the WCS and so the correct transformations are still implemented. Do you agree with this or would you say that the projection used leads to a fundamentally different types of latitude and longitude?
> 
> Finally, `lat`/`lon`, defined whether the property is latitude or longitude.
> 
> Let me know your thoughts and whether you have any suggestions or questions.

Hi,

Thank you for the very detailed reply. Your suggestions look great to me.

Just one thing which might need to be clarified. _CEA_ stands for cylindrical equal area projection. It is different from _TAN_ which stands for gnomonic projection. I don't know whether the CEA projection is already implemented in the ndcube package, I guess no? 

_HPRZ_ is a helioprojective analog of Heliocentric observerward distance (_SOLZ_), standing for the distance from the solar center.

About the definitions, please refer to this paper _Coordinate systems for solar image data_ by W. T. Thompson

**Comment by DanRyanIrish** [comment]
I have opened a [PR to astropy](https://github.com/astropy/astropy/pull/10965) to add these changes.
