### ISSUE TITLE
Supply global_coords during NDCube Initialization?

### ISSUE THREAD

**Issue by DanRyanIrish** [sunpy/ndcube#408]
### Description

In order to stay consistent with `extra_coords`, should it be possible to supply a `GlobalCoords` instance while initializing and `NDCube`?  If so, what should the API look like?

Currently when an `NDCube` is initialized, an empty `GlobalCoords` instance is created and attached via the `extra_coords` attribute.  Global coords must then be added subsequently.

**Comment by adwaitbhope** [comment]
Hi @DanRyanIrish, can I take this up?
I can add a `global_coords` parameter next to `extra_coords` during initialization, and have it follow similar steps as `extra_coords`.

**Comment by Cadair** [comment]
@adwaitbhope At this point I think this issue is more a place to have a discussion rather than something to implement.

I am not sure we actually want this at all. My reasoning for this is mainly that I can't think of a good API for it. Pre-constructing a GlobalCoords object would be counter intuitive as the constructor currently only takes a NDCube instance.

What usecase does adding this to the constructor solve that calling `cube.global_coords.add` after the cube is constructed not address?

**Comment by adwaitbhope** [comment]
Oh, got it.

Would it help that the behavior would be consistent with `extra_coords`?

**Comment by DanRyanIrish** [comment]
Hi @adwaitbhope.  Thanks so much for your enthusiasm.  I'd echo what @Cadair said.  Whether this should be supported is not at all clear at this point.  My feeling is that we should punt this question to after the release of 2.0.  Although it could potentially lead to an API change which isn't ideal, it should be a completely backwards compatible change.  Therefore, in the spirit of being minimalist, maybe it's better to wait to see whether there is a demand for such an API.

**Comment by DanRyanIrish** [comment]
Decision arrived at through #415 is No.  Global_coords should not be included in NDCube contructor.  But for consistency, Extra_coords is also removed.  Extra_coords and global_coords now act quite similarly.
