### ISSUE TITLE
Make a decision about extra_coords in NDCubeBase

### ISSUE THREAD

**Issue by Cadair** [sunpy/ndcube#43]
We should decide if we want the whole `extra_coords` machinery to be an integral part of the `NDCubeBase` API or if we want to allow it to be an optional extra implemented by `NDCube` but not other things that adhere to the protocol.

Pros:

* Not all data will need `extra_coords` so as more use cases appear it might become more of a burden.
* In *theory* the functionality of `extra_coords` should be provided by the wcs object itself, not bolted on in NDCube.

Cons:

* `extra_coords` as currently implemented is pretty deeply integrated with `NDCube` and a subclass of `NDCubeBase` that doesn't have it would not be supported by the likes of IRISPy.

**Comment by DanRyanIrish** [comment]
What are the pros and cons of subclassing ```NDCube``` if you want ```extra_coords``` rather than ```NDCubeBase```?

**Comment by DanRyanIrish** [comment]
Having thought about this issue, my thinking has got me this at this point, regarding the case for keeping extra_coords in ```NDCubeBase```.  
* Although ```extra_coords``` are not needed for all types of data, it gives a scientific user a lot of flexibility to add information as a coordinate which may be very useful to their analysis.
* If ```extra_coords``` are not needed, the attribute does not have to be used.  It's an optional kwarg on instantiation.
* Leaving ```extra_coords``` in required less work to extract it out so that any ```NDCubeBase``` object would be sure to still work.

**Comment by DanRyanIrish** [comment]
On the other hand, extra_coords are not necessarily needed and so leaving them out of Base would be in keeping with the philosophy of minimalism we’ve generally followed with ndcube. This seems a compelling argument to me.

**Comment by DanRyanIrish** [comment]
If we are to leave extra_coords out of NDCube, this begs the question whether there should also be an NDCubeSequenceBase that doesn’t carry the extra_coord support either, e.g. NDCubeSequence.common_axis_extra_coords

**Comment by DanRyanIrish** [comment]
Decision.  ```extra_coords``` will not be in ```NDCubeBase```.  This action is taken in PR #50.
