### ISSUE TITLE
Axes and tick labels do not respect `plot_axes` when the `axes=` keyword argument is used in `plot`

### ISSUE THREAD

**Issue by wtbarnes** [sunpy/ndcube#510]
### Description

When using `.plot`, the `plot_axes` keyword is ignored when labeling the the ticks and axes if a custom WCSAxes instance is passed through the `axes` keyword. `plot_axes` has the expected effect when the `axes` keyword argument is not used. 

### Steps to Reproduce

Consider the following cube, a stationary Gaussian curve smeared in time.

```python
import ndcube
from ndcube.extra_coords import QuantityTableCoordinate
import astropy.units as u
import matplotlib.pyplot as plt
import numpy as np
time = np.linspace(0,1000,500) * u.s
space = np.linspace(0,50,100) * u.Mm
lookup = (QuantityTableCoordinate(space, names='s', physical_types='pos.cartesian') &
          QuantityTableCoordinate(time, names='t', physical_types='time'))
data = np.tile(np.exp(-(space - space[space.shape[0]//2])**2/(4*(space[1]-space[0]))**2),time.shape+(1,),)
cube = ndcube.NDCube(data, lookup.wcs)
```

I can plot it with time on the x or y axes using the `plot_axes` kwarg,

```python
cube.plot()
```
![image](https://user-images.githubusercontent.com/8676141/146398704-642bf08c-5542-4f73-8850-7b979840a03f.png)

```python
cube.plot(plot_axes=('x','y'))
```
![image](https://user-images.githubusercontent.com/8676141/146398868-d5bb3da0-740d-4b6a-8b04-04c1673a3ab3.png)

However, if I then first create an axes instance and pass it to `plot`, along with `plot_axes`, the axes and tick labels are incorrectly placed, seemingly ignoring the `plot_axes` kwarg,

```python
fig = plt.figure()
ax = fig.add_subplot(111, projection=cube.wcs)
cube.plot(axes=ax, plot_axes=('x','y'))
```
![image](https://user-images.githubusercontent.com/8676141/146399248-0752b0fd-b88e-4f70-973a-fcd6db3992c5.png)

### System Details

- ndcube Version: 2.0.0
- SunPy Version: 3.1.1
- Astropy Version: 4.3.1
- Python Version: 3.9
- OS information: Ubuntu 18.04.6 LTS x86_64

**Comment by Cadair** [comment]
I think the root of the issue here is that `plot_axes` is used to generate the `slices=` kwarg to `WCSAxes` and you are not specifying that kwarg in the same way when constructing your custom axes.

I think the offending code is here:

https://github.com/sunpy/ndcube/blob/b8887b3f0f81e1ed1d46e4b0495b2b012ac60eae/ndcube/visualization/mpl_plotter.py#L156-L157

I would propose that a fix might be something like:

```
if axes and plot_axes:
    axes.reset_wcs(wcs=wcs, slices=plot_axes)
```

although we might want to consider throwing a warning or an info log there because that might undo something someone has done purposefully.
