### ISSUE TITLE
Cannot update NDCollection when aligned_axes is None

### ISSUE THREAD

**Issue by jmbhughes** [sunpy/ndcube#576]
### Describe the bug

If either NDCollection has `aligned_axes=None` when you try to update a NDCollection, an error `TypeError: 'NoneType' object is not subscriptable` is thrown. I believe this is undesired behavior. 

### To Reproduce

```py
import astropy.wcs
import numpy as np

from ndcube import NDCube, NDCollection

data = np.random.rand(4, 4, 5)
wcs = astropy.wcs.WCS(naxis=3)
wcs.wcs.ctype = 'WAVE', 'HPLT-TAN', 'HPLN-TAN'
wcs.wcs.cunit = 'Angstrom', 'deg', 'deg'
wcs.wcs.cdelt = 0.2, 0.5, 0.4
wcs.wcs.crpix = 0, 2, 2
wcs.wcs.crval = 10, 0.5, 1
wcs.wcs.cname = 'wavelength', 'HPC lat', 'HPC lon'

cube1 = NDCube(data, wcs=wcs)
cube2 = NDCube(data, wcs=wcs)
cube3 = NDCube(data, wcs=wcs)

collection1 = NDCollection([("cube1", cube1), ("cube2", cube2)])
collection2 = NDCollection([("cube3", cube3)])

collection1.update(collection2)  # throws an error
```

### System Details

-ndcube version 2.0.3
-Python 3.9

### Installation method

pip

**Comment by DanRyanIrish** [comment]
Hi @jmbhughes.  Thank you so much for raising this issue.  This bug is fixed in the development version.  I am hoping that we will soon be releasing v2.1 which will include this fix.  If this is delayed however, we should probably issue a bugfix release sooner.  If you need the fix urgently you can install the development version of ndcube.

**Comment by jmbhughes** [comment]
Super! Thanks.
