### ISSUE TITLE
Importing NDCube results in source observer error on reproject

### ISSUE THREAD

**Issue by lowderchris** [sunpy/ndcube#614]
### Describe the bug

When reprojecting data between WCSs using the reproject package, importing NDCube triggers an error, despite not being used in that chunk of code. When not imported, the reprojection works without error. Do you have any idea of why this might be happening, or am I breaking something by being dense? Details of the error are below. Thank you for your help with this!

```
Traceback (most recent call last):
  File "/Users/clowder/work/punch/projection/reprojection_bugreport.py", line 35, in <module>
    data_2 = output_data = reproject.reproject_adaptive((input_data, input_wcs), output_wcs, output_shape,
  File "/Users/clowder/Library/Python/3.10/lib/python/site-packages/reproject/adaptive/high_level.py", line 166, in reproject_adaptive
    return _reproject_adaptive_2d(
  File "/Users/clowder/Library/Python/3.10/lib/python/site-packages/reproject/adaptive/core.py", line 153, in _reproject_adaptive_2d
    map_coordinates(
  File "reproject/adaptive/deforest.pyx", line 258, in reproject.adaptive.deforest.map_coordinates
  File "/Users/clowder/Library/Python/3.10/lib/python/site-packages/reproject/adaptive/core.py", line 23, in __call__
    pixel_in = pixel_to_pixel(self.wcs_out, self.wcs_in, *pixel_out)
  File "/Users/clowder/Library/Python/3.10/lib/python/site-packages/astropy/wcs/utils.py", line 854, in pixel_to_pixel
    pixel_outputs = wcs_out.world_to_pixel(*world_outputs)
  File "/Users/clowder/Library/Python/3.10/lib/python/site-packages/astropy/wcs/wcsapi/high_level_api.py", line 315, in world_to_pixel
    world_values = high_level_objects_to_values(
  File "/Users/clowder/Library/Python/3.10/lib/python/site-packages/astropy/wcs/wcsapi/high_level_api.py", line 196, in high_level_objects_to_values
    objects[key] = world_by_key[key].transform_to(kwargs["frame"])
  File "/Users/clowder/Library/Python/3.10/lib/python/site-packages/astropy/coordinates/sky_coordinate.py", line 702, in transform_to
    new_coord = trans(self.frame, generic_frame)
  File "/Users/clowder/Library/Python/3.10/lib/python/site-packages/astropy/coordinates/transformations.py", line 1579, in __call__
    curr_coord = t(curr_coord, curr_toframe)
  File "/Users/clowder/Library/Python/3.10/lib/python/site-packages/astropy/coordinates/transformations.py", line 1145, in __call__
    return supcall(fromcoord, toframe)
  File "/Users/clowder/Library/Python/3.10/lib/python/site-packages/sunpy/coordinates/transformations.py", line 261, in wrapped_func
    result = func(*args, **kwargs)
  File "/Users/clowder/Library/Python/3.10/lib/python/site-packages/sunpy/coordinates/transformations.py", line 577, in hpc_to_hpc
    if _observers_are_equal(from_coo.observer, to_frame.observer) and \
  File "/Users/clowder/Library/Python/3.10/lib/python/site-packages/sunpy/coordinates/transformations.py", line 285, in _observers_are_equal
    raise ConvertError("The source observer is set to None, but the transformation requires "
astropy.coordinates.errors.ConvertError: The source observer is set to None, but the transformation requires the source observer to be specified, as the destination observer is set to <HeliographicStonyhurst Coordinate (obstime=2011-06-07T06:33:07.840, rsun=696000.0 km): (lon, lat, radius) in (deg, deg, m)
    (0.07764161, 0.048602, 1.51846027e+11)>.
```

### To Reproduce

``` python
import numpy as np

from ndcube import NDCube   # Commenting out this line will run with no errors

import reproject

from astropy.wcs import WCS
from astropy.io import fits

from sunpy.data.sample import AIA_193_IMAGE

with fits.open(AIA_193_IMAGE) as hdul:
    input_data = hdul[1].data
    input_wcs = WCS(hdul[1].header)

output_shape = (4096, 4096)
output_wcs = WCS(naxis=2)
output_wcs.wcs.crpix = output_shape[1]/2, output_shape[0]/2
output_wcs.wcs.crval = 0, 0
output_wcs.wcs.cdelt = 0.0225, 0.0225
output_wcs.wcs.ctype = "HPLN-ARC", "HPLT-ARC"

data_2 = output_data = reproject.reproject_adaptive((input_data, input_wcs), output_wcs, output_shape, 
                                                    roundtrip_coords=False, return_footprint=False, 
                                                    kernel='Gaussian', boundary_mode='strict')
```

### System Details

sunpy: 4.1.4
astropy: 5.2.2
ndcube: 2.1.1
reproject: 0.10.0

python: 3.10.10

OS: Mac OS 13.3.1
Arch: 64bit, (arm)

### Installation method

pip

**Comment by wtbarnes** [comment]
Thanks for minimal working example!

This exception is actually triggered by `import sunpy.coordinates` (you can confirm this by replacing the `ndcube` import with this). `ndcube` imports `sunpy.coordinates` so the `ndcube` import triggers this implicitly.

The import bit of the traceback is a bit buried at the very end:
```
astropy.coordinates.errors.ConvertError: The source observer is set to None, but the transformation requires the source observer to be specified, as the destination observer is set to <HeliographicStonyhurst Coordinate (obstime=2011-06-07T06:33:07.840, rsun=696000.0 km): (lon, lat, radius) in (deg, deg, m)
    (0.07764161, 0.048602, 1.51846027e+11)>.
```

In calling reproject, you're transforming each `input_wcs` pixel location to the `output_wcs` pixel location. This transform requires transforming from the world coordinate system of `input_wcs` (in this case observer-dependent HPC) to the world coordinate system of `output_wcs`. **In your case, `output_wcs` is an observer-dependent frame but has no observer defined.** This means that the resulting world coordinate transform is not well defined.

The reason this import triggers this error is because `sunpy.coordinates` modifies the `astropy.coordinates` transform graph to include the solar coordinate frames defined in `sunpy.coordinates`. Because `input_wcs` includes an observer location expressed in Heliographic Stonyhurst coordinates (you can see this in the `HGLN,HGLT` keys), this has the effect of the `input_wcs` now having an observer location associated with it.

The solution here is to add observer location information to `output_wcs`. If you want to assume that `output_wcs` has the same observer location as `input_wcs`, the easiest way to do this is to create a copy of `input_wcs` and modify the `output_wcs` as needed such that `output_wcs` picks up the need observer location information,

```python
output_shape = (4096, 4096)
output_wcs = input_wcs.copy()
output_wcs.wcs.crpix = output_shape[1]/2, output_shape[0]/2
output_wcs.wcs.crval = 0, 0
output_wcs.wcs.cdelt = 0.0225, 0.0225
output_wcs.wcs.ctype = "HPLN-ARC", "HPLT-ARC"
```

Also note that [the header helper function in `sunpy` provides a slightly less awkward way to construct a header](https://docs.sunpy.org/en/stable/generated/api/sunpy.map.header_helper.make_fitswcs_header.html#sunpy.map.header_helper.make_fitswcs_header) that can then be passed to `astropy.wcs.WCS` to construct the resulting WCS.

**Comment by lowderchris** [comment]
Aha, thank you for the insight and help there! I tried the SunPy helper function you mentioned to make a similar example where the observer does appear to be defined correctly.

```python
output_coord = SkyCoord(0*u.arcsec, 0*u.arcsec, obstime="2017-08-01", 
                        observer = 'earth', frame=frames.Helioprojective)
output_header = sunpy.map.make_fitswcs_header((4096, 4096), output_coord, 
                                              scale=(0.0225,0.0225)*u.degree/u.pixel, 
                                              projection_code="ARC")
output_wcs = WCS(output_header)
```

Mainly I wanted to document it in case anyone else references this issue, including future me.

Thanks again!
